services:
  frontend:
    build: ./Frontend
    ports:
      - "80:5173"
    stdin_open: true
    networks:
      - mern-app
    environment:
      - CHOKIDAR_USEPOLLING=true
    restart: unless-stopped

  backend:
    depends_on:
      - database
    build: ./backend
    ports:
      - "5000:5000"
    networks:
      - mern-app
    restart: unless-stopped

  database:
    image: mongo:4.0-xenial
    ports:
      - "27017:27017"
    networks:
      - mern-app
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

networks:
  mern-app:
    driver: bridge
volumes:
  mongo-data:
    driver: local
  afro-music: